name: tf-checks
permissions:
  id-token: write
on:
  pull_request:
jobs:
  memcached:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/memcached/'
      provider: aws
      enable_plan: true
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  redis:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/redis/'
      provider: aws
      enable_plan: true
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  redis-cluster:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/redis-cluster/'
      provider: aws
      enable_plan: true
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  valkey:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/valkey/'
      provider: aws
      enable_plan: true
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
